FLAGS=-Wall -g
CC=gcc
CFLAGS=--std=c99 -g -pedantic -Wall -lm
SOURCES := $(wildcard ex[0-9]*.c)
#all: ex19 ex20 ex21 ex22 ex23 ex24 ex25 ex26 ex27 ex28 ex29 ex30 ex31 ex32 ex33 ex34 ex35

all: $(wildcard ex[0-9]*.c)

ex19: object.o

clean:
	  rm -f ex19 object.o

test: 
	test_game
	./test_game

